In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [2]:
df = pd.read_csv('/Users/damaso/Documents/Proyectos/java/IA/data/premierleague/epl_final.csv')

In [3]:
def drop_labels(df: pd.DataFrame, class_name):
    return df.drop(class_name, axis=1)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9380 entries, 0 to 9379
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Season             9380 non-null   object
 1   MatchDate          9380 non-null   object
 2   HomeTeam           9380 non-null   object
 3   AwayTeam           9380 non-null   object
 4   FullTimeHomeGoals  9380 non-null   int64
 5   FullTimeAwayGoals  9380 non-null   int64
 6   FullTimeResult     9380 non-null   object
 7   HalfTimeHomeGoals  9380 non-null   int64
 8   HalfTimeAwayGoals  9380 non-null   int64
 9   HalfTimeResult     9380 non-null   object
 10  HomeShots          9380 non-null   int64
 11  AwayShots          9380 non-null   int64
 12  HomeShotsOnTarget  9380 non-null   int64
 13  AwayShotsOnTarget  9380 non-null   int64
 14  HomeCorners        9380 non-null   int64
 15  AwayCorners        9380 non-null   int64
 16  HomeFouls          9380 non-null   int64
 17  AwayFouls          9380 non-null   int64
 18  HomeYellowCards    9380 non-null   int64
 19  AwayYellowCards    9380 non-null   int64
 20  HomeRedCards       9380 non-null   int64
 21  AwayRedCards       9380 non-null   int64
dtypes: int64(16), object(6)
memory usage: 1.6+ MB

In [5]:
df.describe()

,FullTimeHomeGoals,FullTimeAwayGoals,HalfTimeHomeGoals,HalfTimeAwayGoals,HomeShots,AwayShots,HomeShotsOnTarget,AwayShotsOnTarget,HomeCorners,AwayCorners,HomeFouls,AwayFouls,HomeYellowCards,AwayYellowCards,HomeRedCards,AwayRedCards
count,9380.000000,9380.000000,9380.000000,9380.000000,9380.000000,9380.000000,9380.000000,9380.000000,9380.000000,9380.000000,9380.000000,9380.000000,9380.000000,9380.000000,9380.000000,9380.000000
mean,1.535394,1.182623,0.688273,0.518763,13.617484,10.810661,5.973134,4.693710,6.040299,4.774733,11.276333,11.765672,1.468124,1.792431,0.062473,0.085288
std,1.305432,1.157414,0.835079,0.735357,5.356424,4.696501,3.267954,2.750045,3.110619,2.749541,3.750250,3.924179,1.217190,1.288481,0.253221,0.290183
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,0.000000,0.000000,0.000000,10.000000,7.000000,4.000000,3.000000,4.000000,3.000000,9.000000,9.000000,1.000000,1.000000,0.000000,0.000000
50%,1.000000,1.000000,0.000000,0.000000,13.000000,10.000000,6.000000,4.000000,6.000000,4.000000,11.000000,12.000000,1.000000,2.000000,0.000000,0.000000
75%,2.000000,2.000000,1.000000,1.000000,17.000000,14.000000,8.000000,6.000000,8.000000,6.000000,14.000000,14.000000,2.000000,3.000000,0.000000,0.000000
max,9.000000,9.000000,5.000000,5.000000,43.000000,37.000000,24.000000,20.000000,20.000000,19.000000,33.000000,29.000000,7.000000,9.000000,3.000000,2.000000

In [6]:
df = drop_labels(df, ['Season', 'FullTimeHomeGoals', 'FullTimeAwayGoals', 'HalfTimeHomeGoals','HalfTimeAwayGoals','HalfTimeResult','HomeShots','AwayShots', 'HomeShotsOnTarget', 'AwayShotsOnTarget', 'HomeCorners',  'AwayCorners', 'HomeFouls','AwayFouls','HomeYellowCards','AwayYellowCards','HomeRedCards','AwayRedCards'])
df.head(5)

    MatchDate  HomeTeam       AwayTeam FullTimeResult
0  2000-08-19  Charlton       Man City              H
1  2000-08-19   Chelsea       West Ham              H
2  2000-08-19  Coventry  Middlesbrough              A
3  2000-08-19     Derby    Southampton              D
4  2000-08-19     Leeds        Everton              H

In [7]:
df[['MatchDateYear', 'MatchDateMonth', 'MatchDateDay']] = df['MatchDate'].str.split('-', expand=True)
df = drop_labels(df, ['MatchDate'])
df.head(5)

,HomeTeam,AwayTeam,FullTimeResult,MatchDateYear,MatchDateMonth,MatchDateDay
0,Charlton,Man City,H,2000,08,19
1,Chelsea,West Ham,H,2000,08,19
2,Coventry,Middlesbrough,A,2000,08,19
3,Derby,Southampton,D,2000,08,19
4,Leeds,Everton,H,2000,08,19

In [8]:
df = df[['MatchDateYear', 'MatchDateMonth', 'MatchDateDay', 'HomeTeam', 'AwayTeam','FullTimeResult']]
df.head(5)

,MatchDateYear,MatchDateMonth,MatchDateDay,HomeTeam,AwayTeam,FullTimeResult
0,2000,08,19,Charlton,Man City,H
1,2000,08,19,Chelsea,West Ham,H
2,2000,08,19,Coventry,Middlesbrough,A
3,2000,08,19,Derby,Southampton,D
4,2000,08,19,Leeds,Everton,H

In [9]:
df.loc[df['FullTimeResult'] == 'H', 'FullTimeResult'] = 0
df.loc[df['FullTimeResult'] == 'D', 'FullTimeResult'] = 1
df.loc[df['FullTimeResult'] == 'A', 'FullTimeResult'] = 2
df

,MatchDateYear,MatchDateMonth,MatchDateDay,HomeTeam,AwayTeam,FullTimeResult
0,2000,08,19,Charlton,Man City,0
1,2000,08,19,Chelsea,West Ham,0
2,2000,08,19,Coventry,Middlesbrough,2
3,2000,08,19,Derby,Southampton,1
4,2000,08,19,Leeds,Everton,0
...,...,...,...,...,...,...
9375,2025,05,04,Brentford,Man United,0
9376,2025,05,04,Brighton,Newcastle,1
9377,2025,05,04,West Ham,Tottenham,1
9378,2025,05,04,Chelsea,Liverpool,0
9379,2025,05,05,Crystal Palace,Nott'm Forest,1

In [10]:
df.to_csv('premier_league_data.csv', index=False)

In [ ]:
df['HomeTeam'].value_counts()

HomeTeam
Everton             471
Tottenham           469
Man United          469
Chelsea             469
Arsenal             468
Liverpool           467
Man City            450
Newcastle           430
West Ham            417
Aston Villa         412
Fulham              335
Southampton         318
Sunderland          266
Leicester           245
West Brom           244
Crystal Palace      244
Wolves              204
Bolton              204
Blackburn           204
Stoke               190
Middlesbrough       187
Burnley             171
Wigan               152
Brighton            151
Bournemouth         150
Watford             133
Swansea             133
Leeds               131
Norwich             131
Birmingham          130
Charlton            128
Portsmouth          128
Hull                 95
Sheffield United     76
Brentford            75
Reading              57
QPR                  57
Derby                57
Ipswich              55
Nott'm Forest        55
Cardiff              38
Huddersfield         38
Blackpool            19
Bradford             19
Coventry             19
Luton                19
Name: count, dtype: int64